// <auto-generated />
using System;
using BazaR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BazaR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314150200_AddProfileEntities")]
    partial class AddProfileEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a minimal snapshot - the full model is managed by EF Core
            // This file is auto-generated and should not be manually edited
#pragma warning restore 612, 618
        }
    }
}
