// <auto-generated />
using System;
using BazaR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BazaR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311074405_imageToCategory")]
    partial class imageToCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BazaR.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Brands_Name");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "/images/brands/samsung.png",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Logo = "/images/brands/apple.png",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 3,
                            Logo = "/images/brands/xiaomi.png",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 4,
                            Logo = "/images/brands/sony.png",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 5,
                            Logo = "/images/brands/lg.png",
                            Name = "LG"
                        },
                        new
                        {
                            Id = 6,
                            Logo = "/images/brands/bosch.png",
                            Name = "Bosch"
                        },
                        new
                        {
                            Id = 7,
                            Logo = "/images/brands/adidas.png",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 8,
                            Logo = "/images/brands/nike.png",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 9,
                            Logo = "/images/brands/puma.png",
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 10,
                            Logo = "/images/brands/zara.png",
                            Name = "Zara"
                        },
                        new
                        {
                            Id = 11,
                            Logo = "/images/brands/hm.png",
                            Name = "H&M"
                        },
                        new
                        {
                            Id = 12,
                            Logo = "/images/brands/asus.png",
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 13,
                            Logo = "/images/brands/acer.png",
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 14,
                            Logo = "/images/brands/hp.png",
                            Name = "HP"
                        },
                        new
                        {
                            Id = 15,
                            Logo = "/images/brands/lenovo.png",
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 16,
                            Logo = "/images/brands/dell.png",
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 17,
                            Logo = "/images/brands/canon.png",
                            Name = "Canon"
                        },
                        new
                        {
                            Id = 18,
                            Logo = "/images/brands/epson.png",
                            Name = "Epson"
                        },
                        new
                        {
                            Id = 19,
                            Logo = "/images/brands/makita.png",
                            Name = "Makita"
                        },
                        new
                        {
                            Id = 20,
                            Logo = "/images/brands/dewalt.png",
                            Name = "DeWalt"
                        });
                });

            modelBuilder.Entity("BazaR.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BazaR.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Categories_Name");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("IX_Categories_ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IconUrl = "bi-laptop",
                            Name = "Ноутбуки"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IconUrl = "bi-phone",
                            Name = "Смартфони, ТВ та електроніка"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IconUrl = "bi-controller",
                            Name = "Товари для геймерів"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IconUrl = "bi-fan",
                            Name = "Побутова техніка"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IconUrl = "bi-house",
                            Name = "Товари для дому"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            IconUrl = "bi-tools",
                            Name = "Інструменти та автотовари"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            IconUrl = "bi-droplet",
                            Name = "Сантехніка та ремонт"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            IconUrl = "bi-flower",
                            Name = "Дача, сад та город"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            IconUrl = "bi-bicycle",
                            Name = "Спорт та захоплення"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            IconUrl = "bi-tag",
                            Name = "Одяг, взуття та прикраси"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            IconUrl = "bi-heart",
                            Name = "Краса і здоров'я"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            IconUrl = "bi-emoji-smile",
                            Name = "Дитячі товари"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            IconUrl = "bi-bug",
                            Name = "Зоотовари"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            IconUrl = "bi-pencil",
                            Name = "Канцтовари та книги"
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 15,
                            IconUrl = "bi-cup-straw",
                            Name = "Алкогольні напої та продукти"
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 16,
                            IconUrl = "bi-briefcase",
                            Name = "Товари для бізнесу та послуги"
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 17,
                            IconUrl = "bi-tree",
                            Name = "Тури та відпочинок"
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 18,
                            IconUrl = "bi-percent",
                            Name = "Акції"
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 19,
                            IconUrl = "bi-fire",
                            Name = "Тотальний розпродаж"
                        },
                        new
                        {
                            Id = 101,
                            DisplayOrder = 1,
                            Name = "Asus",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 102,
                            DisplayOrder = 2,
                            Name = "Acer",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 103,
                            DisplayOrder = 3,
                            Name = "HP",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 104,
                            DisplayOrder = 4,
                            Name = "Lenovo",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 105,
                            DisplayOrder = 5,
                            Name = "Dell",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 106,
                            DisplayOrder = 6,
                            Name = "Apple",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 107,
                            DisplayOrder = 7,
                            Name = "Аксесуари для ноутбуків і ПК",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 108,
                            DisplayOrder = 1,
                            Name = "Флеш пам'ять USB",
                            ParentCategoryId = 107
                        },
                        new
                        {
                            Id = 109,
                            DisplayOrder = 2,
                            Name = "Сумки та рюкзаки для ноутбуків",
                            ParentCategoryId = 107
                        },
                        new
                        {
                            Id = 110,
                            DisplayOrder = 3,
                            Name = "Підставки та столики для ноутбуків",
                            ParentCategoryId = 107
                        },
                        new
                        {
                            Id = 111,
                            DisplayOrder = 4,
                            Name = "Веб-камери",
                            ParentCategoryId = 107
                        },
                        new
                        {
                            Id = 120,
                            DisplayOrder = 8,
                            Name = "Комп'ютери",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 121,
                            DisplayOrder = 1,
                            Name = "Монітори",
                            ParentCategoryId = 120
                        },
                        new
                        {
                            Id = 122,
                            DisplayOrder = 2,
                            Name = "Миші",
                            ParentCategoryId = 120
                        },
                        new
                        {
                            Id = 123,
                            DisplayOrder = 3,
                            Name = "Клавіатури",
                            ParentCategoryId = 120
                        },
                        new
                        {
                            Id = 124,
                            DisplayOrder = 4,
                            Name = "Комплект: клавіатури + миші",
                            ParentCategoryId = 120
                        },
                        new
                        {
                            Id = 125,
                            DisplayOrder = 5,
                            Name = "Мережеві сховища (NAS)",
                            ParentCategoryId = 120
                        },
                        new
                        {
                            Id = 130,
                            DisplayOrder = 9,
                            Name = "Комплектуючі",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 131,
                            DisplayOrder = 1,
                            Name = "Відеокарти",
                            ParentCategoryId = 130
                        },
                        new
                        {
                            Id = 132,
                            DisplayOrder = 2,
                            Name = "Жорсткі диски та дискові масиви",
                            ParentCategoryId = 130
                        },
                        new
                        {
                            Id = 133,
                            DisplayOrder = 3,
                            Name = "Процесори",
                            ParentCategoryId = 130
                        },
                        new
                        {
                            Id = 134,
                            DisplayOrder = 4,
                            Name = "SSD",
                            ParentCategoryId = 130
                        },
                        new
                        {
                            Id = 135,
                            DisplayOrder = 5,
                            Name = "Оперативна пам'ять",
                            ParentCategoryId = 130
                        },
                        new
                        {
                            Id = 136,
                            DisplayOrder = 6,
                            Name = "Материнські плати",
                            ParentCategoryId = 130
                        },
                        new
                        {
                            Id = 137,
                            DisplayOrder = 7,
                            Name = "Блоки живлення",
                            ParentCategoryId = 130
                        },
                        new
                        {
                            Id = 140,
                            DisplayOrder = 10,
                            Name = "Мережеве обладнання",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 141,
                            DisplayOrder = 1,
                            Name = "Патч-корди",
                            ParentCategoryId = 140
                        },
                        new
                        {
                            Id = 142,
                            DisplayOrder = 2,
                            Name = "Маршрутизатори",
                            ParentCategoryId = 140
                        },
                        new
                        {
                            Id = 143,
                            DisplayOrder = 3,
                            Name = "IP-камери",
                            ParentCategoryId = 140
                        },
                        new
                        {
                            Id = 144,
                            DisplayOrder = 4,
                            Name = "Комутатори",
                            ParentCategoryId = 140
                        },
                        new
                        {
                            Id = 145,
                            DisplayOrder = 5,
                            Name = "Бездротові точки доступу",
                            ParentCategoryId = 140
                        },
                        new
                        {
                            Id = 150,
                            DisplayOrder = 11,
                            Name = "Серверне обладнання",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 160,
                            DisplayOrder = 12,
                            Name = "Оргтехніка",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 161,
                            DisplayOrder = 1,
                            Name = "БФП/Принтери",
                            ParentCategoryId = 160
                        },
                        new
                        {
                            Id = 162,
                            DisplayOrder = 2,
                            Name = "Проектори",
                            ParentCategoryId = 160
                        },
                        new
                        {
                            Id = 163,
                            DisplayOrder = 3,
                            Name = "Витратні матеріали для принтерів",
                            ParentCategoryId = 160
                        },
                        new
                        {
                            Id = 164,
                            DisplayOrder = 4,
                            Name = "Телефонні апарати",
                            ParentCategoryId = 160
                        },
                        new
                        {
                            Id = 170,
                            DisplayOrder = 13,
                            Name = "Програмне забезпечення",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 171,
                            DisplayOrder = 1,
                            Name = "Операційні системи",
                            ParentCategoryId = 170
                        },
                        new
                        {
                            Id = 172,
                            DisplayOrder = 2,
                            Name = "Офісні програми",
                            ParentCategoryId = 170
                        },
                        new
                        {
                            Id = 173,
                            DisplayOrder = 3,
                            Name = "Антивірусні програми",
                            ParentCategoryId = 170
                        },
                        new
                        {
                            Id = 201,
                            DisplayOrder = 1,
                            Name = "Смартфони",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 202,
                            DisplayOrder = 2,
                            Name = "Телевізори",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 203,
                            DisplayOrder = 3,
                            Name = "Планшети",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 204,
                            DisplayOrder = 4,
                            Name = "Аудіотехніка",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 205,
                            DisplayOrder = 1,
                            Name = "Навушники",
                            ParentCategoryId = 204
                        },
                        new
                        {
                            Id = 206,
                            DisplayOrder = 2,
                            Name = "Колонки",
                            ParentCategoryId = 204
                        },
                        new
                        {
                            Id = 207,
                            DisplayOrder = 3,
                            Name = "MP3-плеєри",
                            ParentCategoryId = 204
                        },
                        new
                        {
                            Id = 208,
                            DisplayOrder = 5,
                            Name = "Фотоапарати",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 209,
                            DisplayOrder = 6,
                            Name = "Відеокамери",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 210,
                            DisplayOrder = 7,
                            Name = "Розумний дім",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 211,
                            DisplayOrder = 8,
                            Name = "Аксесуари до телефонів",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 212,
                            DisplayOrder = 1,
                            Name = "Чохли для телефонів",
                            ParentCategoryId = 211
                        },
                        new
                        {
                            Id = 213,
                            DisplayOrder = 2,
                            Name = "Захисні скельця",
                            ParentCategoryId = 211
                        },
                        new
                        {
                            Id = 214,
                            DisplayOrder = 3,
                            Name = "Зарядні пристрої",
                            ParentCategoryId = 211
                        },
                        new
                        {
                            Id = 215,
                            DisplayOrder = 4,
                            Name = "Power Bank",
                            ParentCategoryId = 211
                        },
                        new
                        {
                            Id = 301,
                            DisplayOrder = 1,
                            Name = "PlayStation",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 302,
                            DisplayOrder = 2,
                            Name = "Xbox",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 303,
                            DisplayOrder = 3,
                            Name = "Nintendo",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 304,
                            DisplayOrder = 4,
                            Name = "Ігрові консолі та приставки",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 305,
                            DisplayOrder = 5,
                            Name = "Джойстики та аксесуари",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 306,
                            DisplayOrder = 6,
                            Name = "Ігри",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 307,
                            DisplayOrder = 7,
                            Name = "Ігрові поверхні",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 308,
                            DisplayOrder = 8,
                            Name = "Ігрові крісла",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 309,
                            DisplayOrder = 9,
                            Name = "Ігрові миші",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 310,
                            DisplayOrder = 10,
                            Name = "Ігрові клавіатури",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 311,
                            DisplayOrder = 11,
                            Name = "Ігрові навушники",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 401,
                            DisplayOrder = 1,
                            Name = "Велика побутова техніка",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 402,
                            DisplayOrder = 1,
                            Name = "Холодильники",
                            ParentCategoryId = 401
                        },
                        new
                        {
                            Id = 403,
                            DisplayOrder = 2,
                            Name = "Пральні машини",
                            ParentCategoryId = 401
                        },
                        new
                        {
                            Id = 404,
                            DisplayOrder = 3,
                            Name = "Плити та духовки",
                            ParentCategoryId = 401
                        },
                        new
                        {
                            Id = 405,
                            DisplayOrder = 4,
                            Name = "Мікрохвильові печі",
                            ParentCategoryId = 401
                        },
                        new
                        {
                            Id = 406,
                            DisplayOrder = 5,
                            Name = "Посудомийні машини",
                            ParentCategoryId = 401
                        },
                        new
                        {
                            Id = 407,
                            DisplayOrder = 2,
                            Name = "Мала побутова техніка",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 408,
                            DisplayOrder = 1,
                            Name = "Пилососи",
                            ParentCategoryId = 407
                        },
                        new
                        {
                            Id = 409,
                            DisplayOrder = 2,
                            Name = "Праски",
                            ParentCategoryId = 407
                        },
                        new
                        {
                            Id = 410,
                            DisplayOrder = 3,
                            Name = "Блендери, міксери",
                            ParentCategoryId = 407
                        },
                        new
                        {
                            Id = 411,
                            DisplayOrder = 4,
                            Name = "Кавомашини",
                            ParentCategoryId = 407
                        },
                        new
                        {
                            Id = 412,
                            DisplayOrder = 5,
                            Name = "Електрочайники",
                            ParentCategoryId = 407
                        },
                        new
                        {
                            Id = 413,
                            DisplayOrder = 6,
                            Name = "Фени",
                            ParentCategoryId = 407
                        },
                        new
                        {
                            Id = 414,
                            DisplayOrder = 3,
                            Name = "Кліматична техніка",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 415,
                            DisplayOrder = 1,
                            Name = "Кондиціонери",
                            ParentCategoryId = 414
                        },
                        new
                        {
                            Id = 416,
                            DisplayOrder = 2,
                            Name = "Обігрівачі",
                            ParentCategoryId = 414
                        },
                        new
                        {
                            Id = 417,
                            DisplayOrder = 3,
                            Name = "Зволожувачі повітря",
                            ParentCategoryId = 414
                        },
                        new
                        {
                            Id = 418,
                            DisplayOrder = 4,
                            Name = "Вентилятори",
                            ParentCategoryId = 414
                        });
                });

            modelBuilder.Entity("BazaR.Models.CategoryBrand", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId", "BrandId");

                    b.HasIndex("BrandId");

                    b.ToTable("CategoryBrands");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            BrandId = 1
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 2
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 3
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 4
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 5
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 12
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 13
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 14
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 15
                        },
                        new
                        {
                            CategoryId = 1,
                            BrandId = 16
                        },
                        new
                        {
                            CategoryId = 201,
                            BrandId = 1
                        },
                        new
                        {
                            CategoryId = 201,
                            BrandId = 2
                        },
                        new
                        {
                            CategoryId = 201,
                            BrandId = 3
                        },
                        new
                        {
                            CategoryId = 201,
                            BrandId = 4
                        },
                        new
                        {
                            CategoryId = 10,
                            BrandId = 7
                        },
                        new
                        {
                            CategoryId = 10,
                            BrandId = 8
                        },
                        new
                        {
                            CategoryId = 10,
                            BrandId = 9
                        },
                        new
                        {
                            CategoryId = 10,
                            BrandId = 10
                        },
                        new
                        {
                            CategoryId = 10,
                            BrandId = 11
                        },
                        new
                        {
                            CategoryId = 9,
                            BrandId = 7
                        },
                        new
                        {
                            CategoryId = 9,
                            BrandId = 8
                        },
                        new
                        {
                            CategoryId = 9,
                            BrandId = 9
                        },
                        new
                        {
                            CategoryId = 6,
                            BrandId = 19
                        },
                        new
                        {
                            CategoryId = 6,
                            BrandId = 20
                        },
                        new
                        {
                            CategoryId = 6,
                            BrandId = 6
                        });
                });

            modelBuilder.Entity("BazaR.Models.CategoryFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryFilters");
                });

            modelBuilder.Entity("BazaR.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Київ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Харків"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Одеса"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Дніпро"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Львів"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Запоріжжя"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Миколаїв"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Вінниця"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Херсон"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Полтава"
                        });
                });

            modelBuilder.Entity("BazaR.Models.Complect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Complects");
                });

            modelBuilder.Entity("BazaR.Models.ComplectItem", b =>
                {
                    b.Property<int>("ComplectId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("ComplectId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("ComplectItems");
                });

            modelBuilder.Entity("BazaR.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("DeliveryTime")
                        .HasColumnType("time");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SendingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SendingPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("BazaR.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Garantia")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("IX_Items_BrandId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_Items_CategoryId");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("IX_Items_IsAvailable");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Items_Name");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Items_Price");

                    b.HasIndex("UserId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = -1000,
                            BrandId = 1,
                            CategoryId = 101,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 101",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1001,
                            BrandId = 1,
                            CategoryId = 101,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 101",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1002,
                            BrandId = 1,
                            CategoryId = 101,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 101",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1003,
                            BrandId = 1,
                            CategoryId = 102,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 102",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1004,
                            BrandId = 1,
                            CategoryId = 102,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 102",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1005,
                            BrandId = 1,
                            CategoryId = 102,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 102",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1006,
                            BrandId = 1,
                            CategoryId = 103,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 103",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1007,
                            BrandId = 1,
                            CategoryId = 103,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 103",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1008,
                            BrandId = 1,
                            CategoryId = 103,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 103",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1009,
                            BrandId = 1,
                            CategoryId = 104,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 104",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1010,
                            BrandId = 1,
                            CategoryId = 104,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 104",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1011,
                            BrandId = 1,
                            CategoryId = 104,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 104",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1012,
                            BrandId = 1,
                            CategoryId = 105,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 105",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1013,
                            BrandId = 1,
                            CategoryId = 105,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 105",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1014,
                            BrandId = 1,
                            CategoryId = 105,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 105",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1015,
                            BrandId = 1,
                            CategoryId = 106,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 106",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1016,
                            BrandId = 1,
                            CategoryId = 106,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 106",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1017,
                            BrandId = 1,
                            CategoryId = 106,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 106",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1018,
                            BrandId = 1,
                            CategoryId = 107,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 107",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1019,
                            BrandId = 1,
                            CategoryId = 107,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 107",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1020,
                            BrandId = 1,
                            CategoryId = 107,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 107",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1021,
                            BrandId = 1,
                            CategoryId = 108,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 108",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1022,
                            BrandId = 1,
                            CategoryId = 108,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 108",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1023,
                            BrandId = 1,
                            CategoryId = 108,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 108",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1024,
                            BrandId = 1,
                            CategoryId = 109,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 109",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1025,
                            BrandId = 1,
                            CategoryId = 109,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 109",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1026,
                            BrandId = 1,
                            CategoryId = 109,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 109",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1027,
                            BrandId = 1,
                            CategoryId = 110,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 110",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1028,
                            BrandId = 1,
                            CategoryId = 110,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 110",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1029,
                            BrandId = 1,
                            CategoryId = 110,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 110",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1030,
                            BrandId = 1,
                            CategoryId = 121,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 121",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1031,
                            BrandId = 1,
                            CategoryId = 121,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 121",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1032,
                            BrandId = 1,
                            CategoryId = 121,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 121",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1033,
                            BrandId = 1,
                            CategoryId = 122,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 122",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1034,
                            BrandId = 1,
                            CategoryId = 122,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 122",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1035,
                            BrandId = 1,
                            CategoryId = 122,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 122",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1036,
                            BrandId = 1,
                            CategoryId = 123,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 123",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1037,
                            BrandId = 1,
                            CategoryId = 123,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 123",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1038,
                            BrandId = 1,
                            CategoryId = 123,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 123",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1039,
                            BrandId = 1,
                            CategoryId = 201,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 201",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1040,
                            BrandId = 1,
                            CategoryId = 201,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 201",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1041,
                            BrandId = 1,
                            CategoryId = 201,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 201",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1042,
                            BrandId = 1,
                            CategoryId = 202,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 202",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1043,
                            BrandId = 1,
                            CategoryId = 202,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 202",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1044,
                            BrandId = 1,
                            CategoryId = 202,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 202",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1045,
                            BrandId = 1,
                            CategoryId = 203,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 203",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1046,
                            BrandId = 1,
                            CategoryId = 203,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 203",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1047,
                            BrandId = 1,
                            CategoryId = 203,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 203",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1048,
                            BrandId = 1,
                            CategoryId = 204,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 204",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1049,
                            BrandId = 1,
                            CategoryId = 204,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 204",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1050,
                            BrandId = 1,
                            CategoryId = 204,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 204",
                            Price = 2500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1051,
                            BrandId = 1,
                            CategoryId = 205,
                            Desc = "Опис товару 1",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 1 категорії 205",
                            Price = 1500,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1052,
                            BrandId = 1,
                            CategoryId = 205,
                            Desc = "Опис товару 2",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 2 категорії 205",
                            Price = 2000,
                            UserId = 1
                        },
                        new
                        {
                            Id = -1053,
                            BrandId = 1,
                            CategoryId = 205,
                            Desc = "Опис товару 3",
                            Garantia = 12,
                            ImageUrl = "/images/items/default.jpg",
                            IsAvailable = true,
                            Name = "Товар 3 категорії 205",
                            Price = 2500,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BazaR.Models.ItemCharacteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemCharacteristics");
                });

            modelBuilder.Entity("BazaR.Models.ItemColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemColors");
                });

            modelBuilder.Entity("BazaR.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ttn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BazaR.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceAtMoment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BazaR.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BazaR.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@example.com",
                            IsAdmin = false,
                            Name = "Test User",
                            PasswordHash = "123456"
                        });
                });

            modelBuilder.Entity("BazaR.Models.Usluga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Uslugi");
                });

            modelBuilder.Entity("BazaR.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("BazaR.Models.CartItem", b =>
                {
                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("CartItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BazaR.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazaR.Models.Category", b =>
                {
                    b.HasOne("BazaR.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("BazaR.Models.CategoryBrand", b =>
                {
                    b.HasOne("BazaR.Models.Brand", "Brand")
                        .WithMany("CategoryBrands")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BazaR.Models.Category", "Category")
                        .WithMany("CategoryBrands")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BazaR.Models.CategoryFilter", b =>
                {
                    b.HasOne("BazaR.Models.Category", "Category")
                        .WithMany("Filters")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BazaR.Models.ComplectItem", b =>
                {
                    b.HasOne("BazaR.Models.Complect", "Complect")
                        .WithMany("Items")
                        .HasForeignKey("ComplectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("ComplectItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Complect");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BazaR.Models.Delivery", b =>
                {
                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("DeliveryVariants")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BazaR.Models.Item", b =>
                {
                    b.HasOne("BazaR.Models.Brand", "Brand")
                        .WithMany("Items")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BazaR.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BazaR.Models.User", "User")
                        .WithMany("SellingItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazaR.Models.ItemCharacteristic", b =>
                {
                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("Characteristics")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BazaR.Models.ItemColor", b =>
                {
                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("Colors")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BazaR.Models.Order", b =>
                {
                    b.HasOne("BazaR.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BazaR.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazaR.Models.OrderItem", b =>
                {
                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BazaR.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BazaR.Models.Review", b =>
                {
                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("Reviews")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BazaR.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazaR.Models.Usluga", b =>
                {
                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("Uslugi")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BazaR.Models.WishlistItem", b =>
                {
                    b.HasOne("BazaR.Models.Item", "Item")
                        .WithMany("WishlistItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BazaR.Models.User", "User")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BazaR.Models.Brand", b =>
                {
                    b.Navigation("CategoryBrands");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("BazaR.Models.Category", b =>
                {
                    b.Navigation("CategoryBrands");

                    b.Navigation("Filters");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("BazaR.Models.Complect", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BazaR.Models.Item", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Characteristics");

                    b.Navigation("Colors");

                    b.Navigation("ComplectItems");

                    b.Navigation("DeliveryVariants");

                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");

                    b.Navigation("Uslugi");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("BazaR.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BazaR.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("SellingItems");

                    b.Navigation("WishlistItems");
                });
#pragma warning restore 612, 618
        }
    }
}
